function isoDate(daysOffset = 0) {
  const baseDate = new Date();
  baseDate.setDate(baseDate.getDate() + daysOffset);
  return baseDate.toISOString();
}

function dateOnly(daysOffset = 0) {
  return isoDate(daysOffset).slice(0, 10);
}

function createDetailRecord(seed) {
  return {
    approvalRecordId: seed.approvalRecordId,
    invoice: {
      approvalRecordId: seed.approvalRecordId,
      booksInvoiceId: seed.booksInvoiceId,
      invoiceNumber: seed.invoiceNumber,
      customerName: seed.customerName,
      invoiceTotal: seed.invoiceTotal,
      currencyCode: seed.currencyCode,
      dueDate: seed.dueDate,
      invoiceDate: seed.invoiceDate,
      booksStatus: seed.booksStatus,
      paymentStatus: seed.paymentStatus,
      crmAccountName: seed.crmContext.crmAccountName,
    },
    lineItems: seed.lineItems,
    crmContext: seed.crmContext,
    approval: {
      approvalStatus: seed.approvalStatus,
      assignedReviewer: seed.assignedReviewer,
      priority: seed.priority,
      exceptionReason: seed.exceptionReason,
      reviewerNotes: seed.reviewerNotes,
      approvalDecisionDate: seed.approvalDecisionDate,
      lastBooksSyncAt: seed.lastBooksSyncAt,
      lastCrmEnrichmentAt: seed.lastCrmEnrichmentAt,
      lastComparedAt: seed.lastComparedAt,
      differenceFound: seed.differenceFound,
      differenceSummary: seed.differenceSummary,
      syncStatus: seed.syncStatus,
    },
    comments: seed.comments,
    audit: seed.audit,
  };
}

export function createMockState() {
  return [
    createDetailRecord({
      approvalRecordId: "APR-1001",
      booksInvoiceId: "BOOKS-INV-70021",
      invoiceNumber: "INV-2026-0045",
      customerName: "Northwind Health Systems",
      invoiceTotal: 18450,
      currencyCode: "USD",
      invoiceDate: dateOnly(-7),
      dueDate: dateOnly(3),
      booksStatus: "Sent",
      paymentStatus: "Unpaid",
      approvalStatus: "Under Review",
      priority: "High",
      assignedReviewer: "Samira Haque",
      exceptionReason: "",
      reviewerNotes: "Confirm implementation milestone sign-off before approval.",
      approvalDecisionDate: "",
      lastBooksSyncAt: isoDate(-1),
      lastCrmEnrichmentAt: isoDate(-1),
      lastComparedAt: isoDate(-1),
      differenceFound: false,
      differenceSummary: "No Difference",
      syncStatus: "Synced",
      lineItems: [
        {
          id: "LI-1",
          name: "Implementation milestone 2",
          description: "Phase 2 implementation delivery",
          quantity: 1,
          rate: 14000,
          discount: 500,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 14175,
        },
        {
          id: "LI-2",
          name: "Training workshop",
          description: "Remote reviewer enablement session",
          quantity: 1,
          rate: 4450,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 4673,
        },
        {
          id: "LI-2B",
          name: "Support add-on",
          description: "Go-live support coverage",
          quantity: 1,
          rate: 800,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 840,
        },
      ],
      crmContext: {
        crmAccountId: "CRM-ACC-1201",
        crmAccountName: "Northwind Health Systems",
        crmDealId: "CRM-DEAL-0082",
        crmDealName: "ERP Rollout Phase 2",
        accountOwner: "Amina Rahman",
        dealStage: "Contracting",
        riskLevel: "Low",
        lastActivityDate: dateOnly(-2),
      },
      comments: [
        {
          id: "COM-1001",
          commentType: "Internal Note",
          comment:
            "Operations requested confirmation that the milestone acceptance email is on file.",
          addedBy: "Samira Haque",
          addedDate: isoDate(-1),
        },
      ],
      audit: [
        {
          id: "AUD-1001",
          eventType: "Status Changed",
          previousStatus: "New",
          newStatus: "Under Review",
          eventMessage:
            "Approval record moved to Under Review after invoice reached the internal queue.",
          actor: "System",
          eventDate: isoDate(-1),
          externalSystem: "Creator",
          externalReferenceId: "APR-1001",
        },
      ],
    }),
    createDetailRecord({
      approvalRecordId: "APR-1002",
      booksInvoiceId: "BOOKS-INV-70022",
      invoiceNumber: "INV-2026-0049",
      customerName: "BluePeak Logistics",
      invoiceTotal: 6200,
      currencyCode: "USD",
      invoiceDate: dateOnly(-5),
      dueDate: dateOnly(5),
      booksStatus: "Draft",
      paymentStatus: "Unpaid",
      approvalStatus: "Needs Clarification",
      priority: "Medium",
      assignedReviewer: "Nabila Noor",
      exceptionReason: "PO number missing from the backup documentation.",
      reviewerNotes:
        "Waiting for the account team to attach the customer PO before the invoice can be cleared.",
      approvalDecisionDate: "",
      lastBooksSyncAt: isoDate(-2),
      lastCrmEnrichmentAt: isoDate(-1),
      lastComparedAt: isoDate(-1),
      differenceFound: true,
      differenceSummary:
        "PO number and billing split need manual validation against the Creator approval snapshot.",
      syncStatus: "Difference Found",
      lineItems: [
        {
          id: "LI-3",
          name: "Warehouse automation subscription",
          description: "Monthly platform license",
          quantity: 2,
          rate: 2500,
          discount: 250,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 4988,
        },
        {
          id: "LI-4",
          name: "Support retainer",
          description: "Priority support package",
          quantity: 1,
          rate: 1200,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 1260,
        },
        {
          id: "LI-4B",
          name: "PO handling fee",
          description: "Documentation processing adjustment",
          quantity: 1,
          rate: 300,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 315,
        },
      ],
      crmContext: {
        crmAccountId: "CRM-ACC-1202",
        crmAccountName: "BluePeak Logistics",
        crmDealId: "CRM-DEAL-0111",
        crmDealName: "Warehouse Automation",
        accountOwner: "Reza Karim",
        dealStage: "Negotiation",
        riskLevel: "Medium",
        lastActivityDate: dateOnly(-1),
      },
      comments: [
        {
          id: "COM-1002",
          commentType: "Clarification Request",
          comment:
            "Please upload the signed PO and confirm whether billing should be split by location.",
          addedBy: "Nabila Noor",
          addedDate: isoDate(-1),
        },
      ],
      audit: [
        {
          id: "AUD-1002",
          eventType: "Clarification Requested",
          previousStatus: "Under Review",
          newStatus: "Needs Clarification",
          eventMessage: "Finance requested PO validation before approval.",
          actor: "Nabila Noor",
          eventDate: isoDate(-1),
          externalSystem: "Creator",
          externalReferenceId: "APR-1002",
        },
      ],
    }),
    createDetailRecord({
      approvalRecordId: "APR-1003",
      booksInvoiceId: "BOOKS-INV-70023",
      invoiceNumber: "INV-2026-0051",
      customerName: "Crescent Retail Group",
      invoiceTotal: 23980,
      currencyCode: "USD",
      invoiceDate: dateOnly(-2),
      dueDate: dateOnly(10),
      booksStatus: "Sent",
      paymentStatus: "Partially Paid",
      approvalStatus: "New",
      priority: "High",
      assignedReviewer: "Unassigned",
      exceptionReason: "",
      reviewerNotes: "",
      approvalDecisionDate: "",
      lastBooksSyncAt: isoDate(-1),
      lastCrmEnrichmentAt: isoDate(-1),
      lastComparedAt: isoDate(-1),
      differenceFound: false,
      differenceSummary: "No Difference",
      syncStatus: "Manual Review",
      lineItems: [
        {
          id: "LI-5",
          name: "POS integration rollout",
          description: "Rollout milestone delivery",
          quantity: 1,
          rate: 19980,
          discount: 980,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 19950,
        },
        {
          id: "LI-6",
          name: "Regional enablement package",
          description: "Regional change-management training",
          quantity: 1,
          rate: 4000,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 4200,
        },
        {
          id: "LI-6B",
          name: "Travel surcharge",
          description: "Regional deployment travel cost",
          quantity: 1,
          rate: 500,
          discount: 0,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 525,
        },
      ],
      crmContext: {
        crmAccountId: "CRM-ACC-1203",
        crmAccountName: "Crescent Retail Group",
        crmDealId: "CRM-DEAL-0124",
        crmDealName: "POS Integration Expansion",
        accountOwner: "Tariq Hasan",
        dealStage: "Closed Won",
        riskLevel: "Low",
        lastActivityDate: dateOnly(-3),
      },
      comments: [],
      audit: [
        {
          id: "AUD-1003",
          eventType: "Record Created",
          previousStatus: "",
          newStatus: "New",
          eventMessage: "Approval record created after Books invoice import.",
          actor: "System",
          eventDate: isoDate(-2),
          externalSystem: "Books",
          externalReferenceId: "BOOKS-INV-70023",
        },
      ],
    }),
    createDetailRecord({
      approvalRecordId: "APR-1004",
      booksInvoiceId: "BOOKS-INV-70024",
      invoiceNumber: "INV-2026-0038",
      customerName: "Evercrest Hotels",
      invoiceTotal: 9100,
      currencyCode: "USD",
      invoiceDate: dateOnly(-15),
      dueDate: dateOnly(-1),
      booksStatus: "Sent",
      paymentStatus: "Unpaid",
      approvalStatus: "Rejected",
      priority: "Low",
      assignedReviewer: "Finance Controller",
      exceptionReason: "Discount mismatch against approved quote.",
      reviewerNotes: "Invoice needs to be reissued with corrected commercial terms.",
      approvalDecisionDate: isoDate(-3),
      lastBooksSyncAt: isoDate(-3),
      lastCrmEnrichmentAt: isoDate(-3),
      lastComparedAt: isoDate(-3),
      differenceFound: true,
      differenceSummary: "Discount terms in Books differ from the approved commercial quote.",
      syncStatus: "Failed",
      lineItems: [
        {
          id: "LI-7",
          name: "Property onboarding package",
          description: "Initial hospitality onboarding setup",
          quantity: 1,
          rate: 9100,
          discount: 300,
          taxName: "VAT",
          taxPercentage: 5,
          itemTotal: 9240,
        },
      ],
      crmContext: {
        crmAccountId: "CRM-ACC-1204",
        crmAccountName: "Evercrest Hotels",
        crmDealId: "CRM-DEAL-0099",
        crmDealName: "Hospitality Package Renewal",
        accountOwner: "Nafisa Islam",
        dealStage: "Closed Won",
        riskLevel: "Medium",
        lastActivityDate: dateOnly(-4),
      },
      comments: [
        {
          id: "COM-1004",
          commentType: "Rejection Note",
          comment: "Quote discount approved at 12 percent, invoice reflects 8 percent.",
          addedBy: "Finance Controller",
          addedDate: isoDate(-3),
        },
      ],
      audit: [
        {
          id: "AUD-1004",
          eventType: "Rejected",
          previousStatus: "Under Review",
          newStatus: "Rejected",
          eventMessage: "Invoice rejected due to discount mismatch against approved quote.",
          actor: "Finance Controller",
          eventDate: isoDate(-3),
          externalSystem: "Creator",
          externalReferenceId: "APR-1004",
        },
      ],
    }),
  ];
}
