const NOW = new Date().toISOString();

function createInvoiceRecord(overrides) {
  return {
    approvalRecordId: overrides.approvalRecordId,
    booksInvoiceId: overrides.booksInvoiceId,
    invoiceNumber: overrides.invoiceNumber,
    customerName: overrides.customerName,
    invoiceTotal: overrides.invoiceTotal,
    currencyCode: overrides.currencyCode ?? "USD",
    dueDate: overrides.dueDate,
    invoiceDate: overrides.invoiceDate,
    booksStatus: overrides.booksStatus ?? "sent",
    paymentStatus: overrides.paymentStatus ?? "unpaid",
    approvalStatus: overrides.approvalStatus ?? "New",
    priority: overrides.priority ?? "Medium",
    crmAccountName: overrides.crmAccountName ?? "",
    crmDealName: overrides.crmDealName ?? "",
    crmOwnerName: overrides.crmOwnerName ?? "",
    assignedReviewer: overrides.assignedReviewer ?? "Finance Ops",
    reviewerEmail: overrides.reviewerEmail ?? "",
    assignmentStatus: overrides.assignmentStatus ?? "Assigned",
    assignedDate: overrides.assignedDate ?? NOW,
    assignmentNote: overrides.assignmentNote ?? "",
    exceptionReason: overrides.exceptionReason ?? "",
    reviewerNotes: overrides.reviewerNotes ?? "",
    decisionDate: overrides.decisionDate ?? "",
    lastActionBy: overrides.lastActionBy ?? "",
    lastActionDate: overrides.lastActionDate ?? "",
    lastEventType: overrides.lastEventType ?? "",
    lastBooksSyncAt: overrides.lastBooksSyncAt ?? NOW,
    lastCrmEnrichmentAt: overrides.lastCrmEnrichmentAt ?? NOW,
    lastComparedAt: overrides.lastComparedAt ?? "",
    differenceFound: overrides.differenceFound ?? null,
    differenceSummary: overrides.differenceSummary ?? "",
    syncStatus: overrides.syncStatus ?? "",
    lineItems: overrides.lineItems ?? [],
    crmContext: overrides.crmContext ?? {},
    comments: overrides.comments ?? [],
    audit: overrides.audit ?? [],
  };
}

export function createMockInvoiceStore() {
  return [
    createInvoiceRecord({
      approvalRecordId: "APR-1001",
      booksInvoiceId: "INV-BOOKS-4421",
      invoiceNumber: "INV-2026-0018",
      customerName: "Northwind Health",
      invoiceTotal: 12450,
      dueDate: "2026-06-28",
      invoiceDate: "2026-06-10",
      booksStatus: "sent",
      paymentStatus: "unpaid",
      approvalStatus: "Under Review",
      priority: "High",
      crmAccountName: "Northwind Health",
      crmDealName: "Phase 1 Rollout",
      crmOwnerName: "Amina Rahman",
      assignedReviewer: "Samira Haque",
      reviewerEmail: "samira.haque@example.com",
      assignmentStatus: "Assigned",
      assignedDate: "2026-06-12T08:30:00Z",
      assignmentNote: "Finance lead requested a final scope confirmation before approval.",
      lastActionBy: "System",
      lastActionDate: "2026-06-12T10:00:00Z",
      lastEventType: "Books Refreshed",
      lastComparedAt: "2026-06-13T10:20:00Z",
      differenceFound: false,
      differenceSummary: "No Difference",
      syncStatus: "Synced",
      lineItems: [
        { id: "L1", name: "Implementation retainer", description: "Phase 1 delivery retainer", quantity: 1, rate: 8000, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 8400 },
        { id: "L2", name: "Data migration setup", description: "Migration and source mapping", quantity: 1, rate: 2500, discount: 200, taxName: "VAT", taxPercentage: 5, itemTotal: 2415 },
        { id: "L3", name: "Training session", description: "Remote enablement workshop", quantity: 1, rate: 1950, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 2048 },
      ],
      crmContext: {
        accountName: "Northwind Health",
        dealName: "Phase 1 Rollout",
        accountManager: "Amina Rahman",
        segment: "Enterprise",
        renewalWindow: "Q4 2026",
      },
      comments: [
        {
          id: "COM-1",
          author: "Samira Haque",
          type: "Internal note",
          body: "Need confirmation that migration scope is included in the signed SOW.",
          createdAt: "2026-06-12T09:30:00Z",
        },
      ],
      audit: [
        {
          id: "AUD-1A",
          eventType: "Books Refreshed",
          summary: "Latest Books snapshot was refreshed for reviewer pickup.",
          actor: "System",
          createdAt: "2026-06-12T10:00:00Z",
        },
        {
          id: "AUD-1",
          eventType: "Status changed",
          summary: "Approval status moved from New to Under Review.",
          actor: "System",
          createdAt: "2026-06-12T08:45:00Z",
        },
      ],
    }),
    createInvoiceRecord({
      approvalRecordId: "APR-1002",
      booksInvoiceId: "INV-BOOKS-4422",
      invoiceNumber: "INV-2026-0020",
      customerName: "BluePeak Logistics",
      invoiceTotal: 5400,
      dueDate: "2026-07-02",
      invoiceDate: "2026-06-14",
      booksStatus: "draft",
      paymentStatus: "unpaid",
      approvalStatus: "Needs Clarification",
      priority: "Medium",
      crmAccountName: "BluePeak Logistics",
      crmDealName: "Warehouse Automation",
      crmOwnerName: "Reza Karim",
      assignedReviewer: "Nabila Noor",
      reviewerEmail: "nabila.noor@example.com",
      assignmentStatus: "Assigned",
      assignedDate: "2026-06-14T09:00:00Z",
      assignmentNote: "Assigned after PO discrepancy was raised by operations.",
      exceptionReason: "PO number missing",
      reviewerNotes: "Client requested split billing but invoice still shows a single line item.",
      lastActionBy: "Nabila Noor",
      lastActionDate: "2026-06-14T13:00:00Z",
      lastEventType: "Clarification Requested",
      lastComparedAt: "2026-06-15T08:10:00Z",
      differenceFound: true,
      differenceSummary: "PO reference and billing structure do not match the Creator approval snapshot.",
      syncStatus: "Difference Found",
      lineItems: [
        { id: "L1", name: "Monthly platform fee", description: "Warehouse automation subscription", quantity: 3, rate: 1200, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 3780 },
        { id: "L2", name: "Support bundle", description: "Priority support and onboarding", quantity: 1, rate: 1800, discount: 180, taxName: "VAT", taxPercentage: 5, itemTotal: 1701 },
        { id: "L3", name: "PO handling fee", description: "Documentation processing adjustment", quantity: 1, rate: 300, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 315 },
      ],
      crmContext: {
        accountName: "BluePeak Logistics",
        dealName: "Warehouse Automation",
        accountManager: "Reza Karim",
        segment: "SMB",
        renewalWindow: "Q1 2027",
      },
      comments: [
        {
          id: "COM-2",
          author: "Nabila Noor",
          type: "Clarification",
          body: "Waiting for Sales to confirm the PO reference before approval.",
          createdAt: "2026-06-14T13:00:00Z",
        },
      ],
      audit: [
        {
          id: "AUD-2A",
          eventType: "Sync Error",
          summary: "Initial Books refresh failed before the clarification request.",
          actor: "System",
          createdAt: "2026-06-14T09:15:00Z",
        },
        {
          id: "AUD-2",
          eventType: "Clarification Requested",
          summary: "Approval halted due to missing PO number.",
          actor: "Nabila Noor",
          createdAt: "2026-06-14T13:00:00Z",
        },
      ],
    }),
    createInvoiceRecord({
      approvalRecordId: "APR-1003",
      booksInvoiceId: "INV-BOOKS-4423",
      invoiceNumber: "INV-2026-0024",
      customerName: "Crescent Retail Group",
      invoiceTotal: 18900,
      dueDate: "2026-06-30",
      invoiceDate: "2026-06-15",
      booksStatus: "sent",
      paymentStatus: "unpaid",
      approvalStatus: "New",
      priority: "High",
      crmAccountName: "Crescent Retail Group",
      crmDealName: "POS Integration Expansion",
      crmOwnerName: "Tariq Hasan",
      assignedReviewer: "Unassigned",
      reviewerEmail: "",
      assignmentStatus: "Unassigned",
      assignedDate: "",
      assignmentNote: "Waiting for reviewer assignment.",
      lastActionBy: "Finance Ops",
      lastActionDate: "2026-06-15T08:00:00Z",
      lastEventType: "Comment Added",
      lastComparedAt: "2026-06-16T06:45:00Z",
      differenceFound: false,
      differenceSummary: "No Difference",
      syncStatus: "Manual Review",
      lineItems: [
        { id: "L1", name: "POS integration milestone 2", description: "Store rollout milestone", quantity: 1, rate: 15000, discount: 500, taxName: "VAT", taxPercentage: 5, itemTotal: 15225 },
        { id: "L2", name: "Regional training package", description: "Onsite training for regional managers", quantity: 1, rate: 3900, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 4095 },
        { id: "L3", name: "Travel surcharge", description: "Regional deployment travel cost", quantity: 1, rate: 500, discount: 0, taxName: "VAT", taxPercentage: 5, itemTotal: 525 },
      ],
      crmContext: {
        accountName: "Crescent Retail Group",
        dealName: "POS Integration Expansion",
        accountManager: "Tariq Hasan",
        segment: "Enterprise",
        renewalWindow: "Q3 2027",
      },
      comments: [],
      audit: [
        {
          id: "AUD-3A",
          eventType: "Comment Added",
          summary: "Reviewer added an internal note before starting approval.",
          actor: "Finance Ops",
          createdAt: "2026-06-15T08:00:00Z",
        },
        {
          id: "AUD-3",
          eventType: "Record created",
          summary: "Approval request created from Books invoice import.",
          actor: "System",
          createdAt: "2026-06-15T07:15:00Z",
        },
      ],
    }),
  ];
}
